name: Main workflow
on: 
  push:
    branches:
      - "dev/**"
env: 
  docker_username: neuhelen 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: my artifact 
          path: . 
  Linting: 
    runs-on: ubuntu-latest
    needs: [Build] 
    steps:
      - name: Download a Build Artifact 
        uses: actions/download-artifact@v4
        with: 
          name: my artifact 
          path: . 
      - name: Run Linting
        uses: super-linter/super-linter/slim@v5 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download a Build Artifact 
        uses: actions/download-artifact@v4
        with: 
          name: my artifact 
          path: . 
      - name: build docker
        run: bash ci/build-docker.sh
